export const QuranInfoArray = [
  {
    quran_name: "Quran",
    language: "Arabic",
    total_verses: 6236,
    total_surahs: 114,
    total_juz: 30,
    total_hizb: 60,
    total_rub_el_hizb: 240,
    total_ayat_al_sajda: 14,
    total_bismillah: 114,
    total_pages: 604,
    details: {
      author: "Allah",
      revelation_period: "Approximately 23 years",
      revelation_place: ["Mecca", "Medina"],
      style: "Classical Arabic",
      method_of_revelation: "Oral and written",
    },
    juz_details: [
      {
        juz_number: 1,
        start_verse: "Al-Fatiha 1:1",
        end_verse: "Al-Baqarah 2:141",
        start_page: 1,
        end_page: 20,
      },
      {
        juz_number: 2,
        start_verse: "Al-Baqarah 2:142",
        end_verse: "Al-Baqarah 2:252",
        start_page: 21,
        end_page: 40,
      },
      {
        juz_number: 3,
        start_verse: "Al-Baqarah 2:253",
        end_verse: "Aali Imran 3:92",
        start_page: 41,
        end_page: 60,
      },
      {
        juz_number: 4,
        start_verse: "Aali Imran 3:93",
        end_verse: "An-Nisa' 4:23",
        start_page: 61,
        end_page: 80,
      },
      {
        juz_number: 5,
        start_verse: "An-Nisa' 4:24",
        end_verse: "An-Nisa' 4:147",
        start_page: 81,
        end_page: 100,
      },
      {
        juz_number: 6,
        start_verse: "An-Nisa' 4:148",
        end_verse: "Al-Ma'idah 5:40",
        start_page: 101,
        end_page: 120,
      },
      {
        juz_number: 7,
        start_verse: "Al-Ma'idah 5:41",
        end_verse: "Al-Ma'idah 5:78",
        start_page: 121,
        end_page: 140,
      },
      {
        juz_number: 8,
        start_verse: "Al-Ma'idah 5:79",
        end_verse: "Al-Anfal 8:1",
        start_page: 141,
        end_page: 160,
      },
      {
        juz_number: 9,
        start_verse: "Al-Anfal 8:2",
        end_verse: "At-Tawbah 9:1",
        start_page: 161,
        end_page: 180,
      },
      {
        juz_number: 10,
        start_verse: "At-Tawbah 9:2",
        end_verse: "Yunus 10:9",
        start_page: 181,
        end_page: 200,
      },
      {
        juz_number: 11,
        start_verse: "Yunus 10:10",
        end_verse: "Hud 11:5",
        start_page: 201,
        end_page: 220,
      },
      {
        juz_number: 12,
        start_verse: "Hud 11:6",
        end_verse: "Yusuf 12:53",
        start_page: 221,
        end_page: 240,
      },
      {
        juz_number: 13,
        start_verse: "Yusuf 12:54",
        end_verse: "Ibrahim 14:11",
        start_page: 241,
        end_page: 260,
      },
      {
        juz_number: 14,
        start_verse: "Ibrahim 14:12",
        end_verse: "Al-Hijr 15:25",
        start_page: 261,
        end_page: 280,
      },
      {
        juz_number: 15,
        start_verse: "Al-Hijr 15:26",
        end_verse: "An-Nahl 16:1",
        start_page: 281,
        end_page: 300,
      },
      {
        juz_number: 16,
        start_verse: "An-Nahl 16:2",
        end_verse: "Al-Isra 17:1",
        start_page: 301,
        end_page: 320,
      },
      {
        juz_number: 17,
        start_verse: "Al-Isra 17:2",
        end_verse: "Al-Kahf 18:75",
        start_page: 321,
        end_page: 340,
      },
      {
        juz_number: 18,
        start_verse: "Al-Kahf 18:76",
        end_verse: "Al-Mu'minun 23:1",
        start_page: 341,
        end_page: 360,
      },
      {
        juz_number: 19,
        start_verse: "Al-Mu'minun 23:2",
        end_verse: "Al-Furqan 25:1",
        start_page: 361,
        end_page: 380,
      },
      {
        juz_number: 20,
        start_verse: "Al-Furqan 25:2",
        end_verse: "At-Tahrim 66:1",
        start_page: 381,
        end_page: 400,
      },
      {
        juz_number: 21,
        start_verse: "At-Tahrim 66:2",
        end_verse: "Al-Mulk 67:1",
        start_page: 401,
        end_page: 420,
      },
      {
        juz_number: 22,
        start_verse: "Al-Mulk 67:2",
        end_verse: "Az-Zumar 39:32",
        start_page: 421,
        end_page: 440,
      },
      {
        juz_number: 23,
        start_verse: "Az-Zumar 39:33",
        end_verse: "At-Tahrim 66:6",
        start_page: 441,
        end_page: 460,
      },
      {
        juz_number: 24,
        start_verse: "At-Tahrim 66:7",
        end_verse: "Al-Baqarah 2:142",
        start_page: 461,
        end_page: 480,
      },
      {
        juz_number: 25,
        start_verse: "Al-Baqarah 2:143",
        end_verse: "An-Nisa' 4:23",
        start_page: 481,
        end_page: 500,
      },
      {
        juz_number: 26,
        start_verse: "An-Nisa' 4:24",
        end_verse: "An-Nisa' 4:147",
        start_page: 501,
        end_page: 520,
      },
      {
        juz_number: 27,
        start_verse: "An-Nisa' 4:148",
        end_verse: "Al-Ma'idah 5:40",
        start_page: 521,
        end_page: 540,
      },
      {
        juz_number: 28,
        start_verse: "Al-Ma'idah 5:41",
        end_verse: "Al-Ma'idah 5:78",
        start_page: 541,
        end_page: 560,
      },
      {
        juz_number: 29,
        start_verse: "Al-Ma'idah 5:79",
        end_verse: "Al-Anfal 8:1",
        start_page: 561,
        end_page: 580,
      },
      {
        juz_number: 30,
        start_verse: "Al-Anfal 8:2",
        end_verse: "An-Naba 78:1",
        start_page: 581,
        end_page: 604,
      },
    ],
    ayat_al_sajda_reference: [
      {
        surah: "Al-A'raf",
        verse: 7,
        verse_number: 206,
        reference: "Quran 7:206",
        prostration_type: "Sunnah",
        details:
          "This verse speaks about the signs of Allah, and it is recommended to perform Sajda as an act of submission to His greatness.",
        hadith_reference:
          "Sahih Muslim, Book 4, Hadith 747: The Prophet (PBUH) would prostrate upon reciting verses that caused prostration.",
      },
      {
        surah: "Ar-Ra'd",
        verse: 13,
        verse_number: 15,
        reference: "Quran 13:15",
        prostration_type: "Sunnah",
        details:
          "This verse emphasizes the signs of Allah in the heavens and the earth, prompting the believer to acknowledge Allah’s greatness through prostration.",
        hadith_reference:
          "Sahih Bukhari, Book 65, Hadith 477: Narrated Abu Huraira: The Messenger of Allah (PBUH) said, 'When the son of Adam recites a verse of prostration and prostrates, the Satan departs.'",
      },
      {
        surah: "An-Nahl",
        verse: 16,
        verse_number: 26,
        reference: "Quran 16:26",
        prostration_type: "Sunnah",
        details:
          "The verse speaks of Allah’s dominion over the earth and skies, leading the believer to prostrate in gratitude.",
        hadith_reference:
          "Sahih Muslim, Book 4, Hadith 747: The Prophet (PBUH) used to prostrate when he recited verses of prostration.",
      },
      {
        surah: "Al-Isra",
        verse: 17,
        verse_number: 109,
        reference: "Quran 17:109",
        prostration_type: "Sunnah",
        details:
          "This verse talks about the reaction of people to the Quran. It highlights the power of the words of Allah, prompting prostration.",
        hadith_reference:
          "Sunan Abu Dawood, Book 6, Hadith 1364: The Prophet (PBUH) said, 'When a verse of prostration is recited to you, prostrate.'",
      },
      {
        surah: "Maryam",
        verse: 19,
        verse_number: 58,
        reference: "Quran 19:58",
        prostration_type: "Sunnah",
        details:
          "This verse refers to those who have followed the righteous path, and it encourages prostration to Allah in recognition of His mercy.",
        hadith_reference:
          "Sahih Bukhari, Book 65, Hadith 477: The Messenger of Allah (PBUH) would prostrate upon hearing the verses of prostration.",
      },
      {
        surah: "Al-Hajj",
        verse: 22,
        verse_number: 18,
        reference: "Quran 22:18",
        prostration_type: "Sunnah",
        details:
          "This verse reminds of the power of Allah and the submission of all things to Him, leading to prostration as a sign of worship.",
        hadith_reference:
          "Sahih Muslim, Book 4, Hadith 747: The Prophet (PBUH) said, 'When you hear a verse of prostration, then perform the prostration.'",
      },
      {
        surah: "Al-Furqan",
        verse: 25,
        verse_number: 60,
        reference: "Quran 25:60",
        prostration_type: "Sunnah",
        details:
          "A verse that highlights the greatness of Allah, where the believers are urged to prostrate when reciting or hearing it.",
        hadith_reference:
          "Sunan Ibn Majah, Hadith 1072: Narrated Abu Huraira: The Messenger of Allah (PBUH) said, 'Prostrate when a verse of prostration is recited.'",
      },
      {
        surah: "An-Naml",
        verse: 27,
        verse_number: 26,
        reference: "Quran 27:26",
        prostration_type: "Sunnah",
        details:
          "This verse talks about the sovereignty of Allah over all things, prompting the believer to express humility through prostration.",
        hadith_reference:
          "Sahih Bukhari, Book 65, Hadith 477: The Prophet (PBUH) said, 'When the verse of prostration is recited to you, prostrate.'",
      },
      {
        surah: "As-Sajda",
        verse: 32,
        verse_number: 15,
        reference: "Quran 32:15",
        prostration_type: "Wajib (Obligatory)",
        details:
          "The verse emphasizes the prostration of the believers to Allah. This verse is considered a mandatory prostration by scholars.",
        hadith_reference:
          "Sahih Muslim, Book 4, Hadith 747: The Prophet (PBUH) said, 'When you come to a verse of prostration, prostrate.'",
      },
      {
        surah: "Sad",
        verse: 38,
        verse_number: 24,
        reference: "Quran 38:24",
        prostration_type: "Sunnah",
        details:
          "This verse highlights the humbling power of Allah’s judgment, encouraging prostration as a form of submission.",
        hadith_reference:
          "Sunan Abu Dawood, Hadith 1365: The Prophet (PBUH) would prostrate when he recited a verse that required prostration.",
      },
      {
        surah: "Al-Inshiqaq",
        verse: 84,
        verse_number: 21,
        reference: "Quran 84:21",
        prostration_type: "Sunnah",
        details:
          "The verse speaks of the earth splitting open, which signifies the awe-inspiring power of Allah, prompting the believer to perform Sajda.",
        hadith_reference:
          "Sahih Muslim, Book 4, Hadith 747: The Prophet (PBUH) prostrated whenever he came across a verse of prostration.",
      },
      {
        surah: "Al-Alaq",
        verse: 96,
        verse_number: 19,
        reference: "Quran 96:19",
        prostration_type: "Wajib (Obligatory)",
        details:
          "This is the final verse of prostration in the Quran, where the command to prostrate is clear, and it is obligatory to do so when reciting or hearing this verse.",
        hadith_reference:
          "Sahih Muslim, Book 4, Hadith 747: The Prophet (PBUH) said, 'When a verse of prostration is recited to you, prostrate immediately.'",
      },
      {
        surah: "Al-Hajj",
        verse: 22,
        verse_number: 18,
        reference: "Quran 22:18",
        prostration_type: "Sunnah",
        details:
          "The verse mentions the worship of Allah and submission, leading to the act of Sajda.",
        hadith_reference:
          "Sahih Muslim, Book 4, Hadith 747: When a verse of prostration is recited, the Prophet (PBUH) used to prostrate.",
      },
      {
        surah: "Al-Ankabut",
        verse: 29,
        verse_number: 14,
        reference: "Quran 29:14",
        prostration_type: "Sunnah",
        details:
          "This verse emphasizes the oppression of the disbelievers and calls the believers to prostrate in humility.",
        hadith_reference:
          "Sunan Abu Dawood, Hadith 1364: The Prophet (PBUH) said, 'Perform the prostration when a verse of prostration is recited to you.'",
      },
    ],
    source: [
      {
        name: "ace-tgkhmahjiddinju",
        author: "Tgk. H. Mahjiddin Jusuf",
        language: "Achinese",
        direction: "ltr",
        source: "https://www.islamic-invitation.com/",
        comments:
          "This translation was OCRed, in case you find any mistakes, let me know at https://bit.ly/33FuNZS",
        link: { orig: "", la: "", lad: "" },
      },
      {
        name: "aar-sheikhmahmoudab",
        author: "Sheikh Mahmoud Abdel Qader Hamz And Group Of Scholars",
        language: "Afar",
        direction: "ltr",
        source: "https://qurancomplex.gov.sa/",
        comments:
          "This translation was OCRed, in case you find any mistakes, let me know at https://bit.ly/33FuNZS",
        link: { orig: "", la: "", lad: "" },
      },
      ,
      {
        language: "Afrikaans",
        name: "afr-imammabaker",
        author: "Imam M. A. Baker",
        direction: "ltr",
        source: "The Islamic Dawah Movement of Southern Africa",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Albanian",
        name: "sqi-unknown-la",
        author: "Unknown",
        direction: "ltr",
        source: "http://www.qurandatabase.org",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Amharic",
        name: "amh-muhammedsadiqan",
        author: "Muhammed Sadiq And Muhammed Sani Habib",
        direction: "ltr",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Arabic",
        name: "ara-quran-la5",
        author: "Quran Transliteration",
        direction: "ltr",
        source: "",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Assamese",
        name: "asm-shaykhrafeequli",
        author: "Shaykh Rafeequl Islam Habibur Rahman",
        direction: "ltr",
        source:
          "https://quranenc.com/check/assamese_rafeeq/v1.0.0-csv.1 , https://quranenc.com/en/browse/assamese_rafeeq , https://quranenc.com ,",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Azerbaijani",
        name: "aze-alikhanmusayev-la",
        author: "Alikhan Musayev",
        direction: "ltr",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Bambara",
        name: "bam-deenmuhammad",
        author: "Deen Muhammad",
        direction: "rtl",
        source: "",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Bengali",
        name: "ben-abubakrzakaria-la",
        author: "Abu Bakr Zakaria",
        direction: "ltr",
        source: "https://qurancomplex.gov.sa/",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Berber",
        name: "ber-ramdaneatmansou-la",
        author: "Ramdane At Mansour",
        direction: "ltr",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Bosnian",
        name: "bos-besimkorkut-la",
        author: "Besim Korkut",
        direction: "ltr",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Bulgarian",
        name: "bul-tzvetantheophan-la",
        author: "Tzvetan Theophanov",
        direction: "ltr",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Burmese",
        name: "mya-alinuyin",
        author: "Alin U Yin",
        direction: "ltr",
        source: "",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Catalan",
        name: "cat-yousseflyoussi-la",
        author: "Youssef Lyoussi",
        direction: "ltr",
        source: "",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Chichewa",
        name: "nya-alhajiyusufmuha",
        author: "Al Haji Yusuf Muhammad Kanyamula",
        direction: "ltr",
        source:
          "http://goodwordbooks.com/, Goodword Books, Islamic Dawah Movement of Southern Africa",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Chinese(Simplified)",
        name: "zho-majian-la",
        author: "Ma Jian",
        direction: "ltr",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Chinese(Traditional)",
        name: "zho-majian1-la",
        author: "Ma Jian",
        direction: "ltr",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Croatian",
        name: "hrv-unknown-la",
        author: "Unknown",
        direction: "ltr",
        source: "http://donatequran.com/",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Czech",
        name: "ces-arnykl-la",
        author: "A. R. Nykl",
        direction: "ltr",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Dagbani",
        name: "dag-muhammadbabaght",
        author: "Muhammad Baba Ghtobo",
        direction: "ltr",
        source: "https://www.islamic-invitation.com",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Dari",
        name: "prs-mawlawimuhammad",
        author: "Mawlawi Muhammad Anwar Badkhashani",
        direction: "rtl",
        source: "https://quranenc.com/en/browse/dari_badkhashani",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Danish",
        name: "dan-hadiabdollahian",
        author: "Hadi Abdollahian",
        direction: "ltr",
        source: "https://www.alqurantranslation.com/ , Contact:+989354664487",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Divehi",
        name: "div-officeofthepres",
        author: "Office Of The President Of Maldives",
        direction: "rtl",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Dutch",
        name: "nld-fredleemhuis",
        author: "Fred Leemhuis",
        direction: "ltr",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "English",
        name: "eng-abdelhaleem",
        author: "Abdel Haleem",
        direction: "ltr",
        source: "",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Esperanto",
        name: "epo-hadiabdollahian",
        author: "Hadi Abdollahian",
        direction: "ltr",
        source: "https://www.alqurantranslation.com/ , Contact:+989354664487",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Filipino",
        name: "fil-abdullatifeduar",
        author: "Abdullatif Eduardo M. Arceo",
        direction: "ltr",
        source:
          "Goodword Books , http://www.goodwordbooks.com/ , Center for Peace and Spirituality , https://www.cpsglobal.org/",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Finnish",
        name: "fin-unknown-la",
        author: "Unknown",
        direction: "ltr",
        source: "",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "French",
        name: "fra-islamicfoundati-la",
        author: "Islamic Foundation",
        direction: "ltr",
        source:
          "https://quranenc.com/check/french_montada/v1.0.0-csv.1 , https://quranenc.com/en/browse/french_montada , https://quranenc.com ,",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Fulah",
        name: "ful-rowadtranslatio",
        author: "Rowad Translation Center And Islamhouse",
        direction: "ltr",
        source: "https://quranenc.com/en/browse/fulani_rwwad",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Ganda",
        name: "lug-fareeqmusa",
        author: "Fareeq Musa",
        direction: "ltr",
        source: "",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "German",
        name: "deu-aburidamuhammad-la",
        author: "Abu Rida Muhammad Ibn Ahmad Ibn Rassoul",
        direction: "ltr",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Gujarati",
        name: "guj-rabilaalomari-la",
        author: "Rabila Al Omari",
        direction: "ltr",
        source: "Al Birr Foundation http://albirr.in/quran-pdf",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Hausa",
        name: "hau-abubakarmahmood-la",
        author: "Abubakar Mahmood Jummi",
        direction: "ltr",
        source:
          "https://quranenc.com/check/hausa_gummi/v1.2.0-csv.1 , https://quranenc.com/en/browse/hausa_gummi , https://quranenc.com ,",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Hebrew",
        name: "heb-darusalamhousei",
        author: "Darusalam House In Jerusalem",
        direction: "rtl",
        source: "https://quranenc.com/en/browse/hebrew_darussalam",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Hindi",
        name: "hin-maulanaazizulha-la",
        author: "Maulana Azizul Haque Al Umari",
        direction: "ltr",
        source:
          "https://quranenc.com/check/hindi_omari/v1.1.0-csv.1 , https://quranenc.com/en/browse/hindi_omari , https://quranenc.com ,",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Hungarian",
        name: "hun-drahmedabdelrah-la",
        author: "Dr. Ahmed Abdel Rahman Okfat Tashaab",
        direction: "ltr",
        source: "https://archive.org/ , King Fahd Quran Complex",
        comments:
          "This translation was OCRed, in case you find any mistakes, let me know at https://bit.ly/33FuNZS",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Indonesian",
        name: "ind-indonesianislam",
        author: "Indonesian Islamic Affairs Ministry",
        direction: "ltr",
        source:
          "https://quranenc.com/check/indonesian_affairs/v1.0.0-csv.1 , https://quranenc.com/en/browse/indonesian_affairs , https://quranenc.com ,",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Iranun",
        name: "ilp-abdulazizgroaal",
        author: "Abdul Aziz Gro Aalem Saromintang",
        direction: "ltr",
        source: "https://www.islamic-invitation.com/ , King Fahd Quran Complex",
        comments:
          "This translation was OCRed, in case you find any mistakes, let me know at https://bit.ly/33FuNZS . This is a Iranon Philippines translation",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Italian",
        name: "ita-hamzarobertopic-la",
        author: "Hamza Roberto Piccardo",
        direction: "ltr",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Japanese",
        name: "jpn-ryoichimita-la",
        author: "Ryoichi Mita",
        direction: "ltr",
        source:
          "https://quranenc.com/check/japanese_meta/v1.0.0-csv.1 , https://quranenc.com/en/browse/japanese_meta , https://quranenc.com ,",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Javanese",
        name: "jav-unknown-la",
        author: "Unknown",
        direction: "ltr",
        source:
          "https://github.com/hakimrie/alQuran-Translations , https://voiceofquran.info/download-quran-translation-pdf/",
        comments:
          "This translation was made by merging two jawa translations from different sources, first source was from Github which was partial i.e chapters from - were missing and to complete the whole quran translation, chapters from - were taken from Lahori Ahmadiyya jawa quran translation book, This was done for the benefit of 80 million muslim javanese speakers as no complete jawanese translation was available for them on the web, incase you find any issues in the translation, please let me know at https://bit.ly/FuNZS",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Kannada",
        name: "kan-abdussalamputhi-la",
        author: "Abdussalam Puthige",
        direction: "ltr",
        source: "http://quraninkannada.com , aputhige@gmail.com",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Kazakh",
        name: "kaz-khalifahaltai-la",
        author: "Khalifah Altai",
        direction: "ltr",
        source: "",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Kendayan",
        name: "knx-unknown",
        author: "Unknown",
        direction: "ltr",
        source: "https://www.islamic-invitation.com",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Khmer",
        name: "khm-cambodianmuslim-la",
        author: "Cambodian Muslim Community Development",
        direction: "ltr",
        source:
          "https://quranenc.com/check/khmer_cambodia/v1.0.0-csv.1 , https://quranenc.com/en/browse/khmer_cambodia , https://quranenc.com ,",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Kinyarwanda",
        name: "kin-rmcrwanda",
        author: "R. M. C. Rwanda",
        direction: "ltr",
        source: "https://www.islamic-invitation.com/",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Kirghiz",
        name: "kir-shamsaldinhakim-la",
        author: "Shams Al Din Hakimov",
        direction: "ltr",
        source: "https://qurancomplex.gov.sa/",
        comments:
          "This translation was OCRed, in case you find any mistakes, let me know at https://bit.ly/33FuNZS",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Korean",
        name: "kor-hamidchoi-la",
        author: "Hamid Choi",
        direction: "ltr",
        source: "https://qurancomplex.gov.sa/",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Kurdish",
        name: "kur-burhanmuhammada",
        author: "Burhan Muhammad Amin",
        direction: "rtl",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Kurmanji",
        name: "kmr-unknown-la",
        author: "Unknown",
        direction: "ltr",
        source: "http://www.maktabah.org , http://donatequran.com/",
        comments: "This language is also known as Northern Kurdish",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Latin",
        name: "lat-hadiabdollahian",
        author: "Hadi Abdollahian",
        direction: "ltr",
        source: "https://www.alqurantranslation.com/ , Contact:+989354664487",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Lingala",
        name: "lin-zakariyamuhamme",
        author: "Zakariya Muhammed Balingongo",
        direction: "ltr",
        source: "https://quranenc.com/en/browse/lingala_zakaria",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Luyia",
        name: "luy-mohammadramadha",
        author:
          "Mohammad Ramadhan Sebwa, Ramadhan Hajj Ndeka, Ismail Were, Musa Murasi Salim Kukuya, Yusuf Shiundu Malala, Yahya Wafula Ojwang, Haroon Albert Msah",
        direction: "ltr",
        source: "https://www.islamic-invitation.com/",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Macedonian",
        name: "mkd-macedonianschol",
        author: "Macedonian Scholars",
        direction: "ltr",
        source: "https://quranenc.com/en/browse/macedonian_group",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Malay",
        name: "msa-abdullahmuhamma",
        author: "Abdullah Muhammad Basmeih",
        direction: "ltr",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Malayalam",
        name: "mal-abdulhameedmada-la",
        author: "Abdul Hameed Madani And Kunhi Mohammed",
        direction: "ltr",
        source: "https://qurancomplex.gov.sa/",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Maltese",
        name: "mlt-martinrzammitmu-la",
        author: "Martin R. Zammit, Muhammad El Sadi",
        direction: "ltr",
        source:
          "World Islamic Call Society(WICS) , https://www.islamic-invitation.com/",
        comments:
          "This translation was OCRed, Please report the mistakes, at https://bit.ly/33FuNZS",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Maranao",
        name: "mrw-guroalimsaroman",
        author: "Guro Alim Saromantang",
        direction: "ltr",
        source: "http://www.qurandatabase.org",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Marathi",
        name: "mar-muhammadshafiia",
        author: "Muhammad Shafi I Ansari",
        direction: "ltr",
        source: "Al Birr Foundation http://albirr.in/quran-pdf",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Nepali",
        name: "nep-ahlalhadithcent-la",
        author: "Ahl Al Hadith Central Society Of Nepal",
        direction: "ltr",
        source: "",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Norwegian",
        name: "nor-einarberg-la",
        author: "Einar Berg",
        direction: "ltr",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Oromo",
        name: "orm-ghaliapapurapag",
        author: "Ghali Apapur Apaghuna",
        direction: "ltr",
        source:
          "https://quranenc.com/check/oromo_ababor/v1.0.0-csv.1 , https://quranenc.com/en/browse/oromo_ababor , https://quranenc.com ,",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Panjabi",
        name: "pan-drmuhamadhabibb-la",
        author:
          "Dr. Muhamad Habib, Bhai Harpreet Singh, Maulana Wahiduddin Khan",
        direction: "ltr",
        source:
          "Goodword Books, http://goodwordbooks.com/ , http://cpsglobal.org/",
        comments:
          "This translation was OCRed, incase you find mistakes, please let me know at https://bit.ly/33FuNZS",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Persian",
        name: "fas-abdolmohammaday",
        author: "Abdolmohammad Ayati",
        direction: "rtl",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Polish",
        name: "pol-jozefabielawski-la",
        author: "Jozefa Bielawskiego",
        direction: "ltr",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Portuguese",
        name: "por-helminasr-la",
        author: "Helmi Nasr",
        direction: "ltr",
        source:
          "https://quranenc.com/check/portuguese_nasr/v1.3.0-csv.1 , https://quranenc.com/en/browse/portuguese_nasr , https://quranenc.com ,",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Pushto",
        name: "pus-abdulwalikhan",
        author: "Abdulwali Khan",
        direction: "rtl",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Romanian",
        name: "ron-georgegrigore-la",
        author: "George Grigore",
        direction: "ltr",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Rundi",
        name: "run-sheikhamissirad",
        author: "Sheikh Amissi Radjabu Ntamba",
        direction: "ltr",
        source: "aradjantas@gmail.com , www.islamic-invitation.com",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Russian",
        name: "rus-abuadel-la",
        author: "Abu Adel",
        direction: "ltr",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Serbian",
        name: "srp-rowwadtranslati",
        author: "Rowwad Translation Center Islamhouse",
        direction: "ltr",
        source: "https://quranenc.com/en/browse/serbian_rwwad",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Shona",
        name: "sna-abdullahjmadini",
        author: "Abdullah J. M. Adini And Students",
        direction: "ltr",
        source: "https://www.islamic-invitation.com/",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Sindhi",
        name: "snd-tajmehmoodamrot",
        author: "Taj Mehmood Amroti",
        direction: "rtl",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Sinhala",
        name: "sin-naseemismailand-la",
        author: "Naseem Ismail And Masoor Maulana, Kaleel",
        direction: "ltr",
        source: "https://alquran.cloud/api",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Slovak",
        name: "slk-hadiabdollahian",
        author: "Hadi Abdollahian",
        direction: "ltr",
        source: "https://www.alqurantranslation.com/ , Contact:+989354664487",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Somali",
        name: "som-abdullahhasanja",
        author: "Abdullah Hasan Jacob",
        direction: "ltr",
        source: "https://quranenc.com/en/browse/somali_yacob",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Sotho",
        name: "sot-sheikheliaskeke",
        author: "Sheikh Elias Keketso Lelia",
        direction: "ltr",
        source: "Islamic Dawah Movement of Southern Africa (IDM)",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Spanish",
        name: "spa-abdulqadermouhe-la",
        author: "Abdul Qader Mouheddine, Sirhan Ali Sanchez.",
        direction: "ltr",
        source: "https://www.islamic-invitation.com/",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Swahili",
        name: "swa-abdullahmuhamma",
        author: "Abdullah Muhammad Abu Bakr",
        direction: "ltr",
        source: "",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Swedish",
        name: "swe-knutbernstrom-la",
        author: "Knut Bernstrom",
        direction: "ltr",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Tajik",
        name: "tgk-abdolmohammaday-la",
        author: "Abdolmohammad Ayati",
        direction: "ltr",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Tamil",
        name: "tam-abdulhameedbaqa-la",
        author: "Abdulhameed Baqavi",
        direction: "ltr",
        source:
          "https://quranenc.com/check/tamil_baqavi/v1.0.0-csv.1 , https://quranenc.com/en/browse/tamil_baqavi , https://quranenc.com ,",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Tatar",
        name: "tat-yakubibnnugman",
        author: "Yakub Ibn Nugman",
        direction: "ltr",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Telugu",
        name: "tel-abdulraheemmoha-la",
        author: "Abdul Raheem Mohammad Moulana",
        direction: "ltr",
        source: "https://qurancomplex.gov.sa/",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Thai",
        name: "tha-groupfromthesoc-la",
        author:
          "Group From The Society Of Graduates Of Thai Universities And Institutes",
        direction: "ltr",
        source: "",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Turkish",
        name: "tur-abdulbakigolpin-la",
        author: "Abdulbaki Golpinarli",
        direction: "ltr",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Twi",
        name: "twi-sheikhharounism",
        author: "Sheikh Haroun Ismaeel",
        direction: "ltr",
        source: "https://quranenc.com/en/browse/asante_harun",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Uighur",
        name: "uig-muhammadsaleh",
        author: "Muhammad Saleh",
        direction: "rtl",
        source: "http://tanzil.net",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Ukrainian",
        name: "ukr-drmikhailoyaqub",
        author: "Dr. Mikhailo Yaqubovic",
        direction: "ltr",
        source: "https://quranenc.com/en/browse/ukrainian_yakubovych",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Urdu",
        name: "urd-abulaalamaududi-la",
        author: "Abul Ala Maududi",
        direction: "ltr",
        source: "https://quranromanurdu.com/",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Uzbek",
        name: "uzb-alaaudeenmansou",
        author: "Alaaudeen Mansour",
        direction: "ltr",
        source: "",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Vietnamese",
        name: "vie-hassanabdulkari-la",
        author: "Hassan Abdulkarim",
        direction: "ltr",
        source: "",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Xhosa",
        name: "xho-imaamismaaeelng",
        author: "Imaam Ismaaeel Ngqoyiyana",
        direction: "ltr",
        source:
          "The Islamic Dawah Movement of Southern Africe(IDM) , https://www.alqurantranslation.com/",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Yau",
        name: "yuw-muhammadbinabdu-la",
        author: "Muhammad Bin Abdul Hamid Silika",
        direction: "ltr",
        source: "https://quranenc.com/en/browse/yaw_silika",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Yoruba",
        name: "yor-shaykhaburahima",
        author: "Shaykh Abu Rahimah Mikael Aykyuni",
        direction: "ltr",
        source:
          "https://quranenc.com/check/yoruba_mikail/v1.0.0-csv.1 , https://quranenc.com/en/browse/yoruba_mikail , https://quranenc.com ,",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
      {
        language: "Zulu",
        name: "zul-iqembulezifundi",
        author:
          "Iqembu Lezifundiswa, Mussa Muhammad Telela , Uthman Mfanafuthi Msomi, Moulana Abdur Rahman Chilipa, Haji Ibrahim Mondli Japhet Mthembu, Moulana Imran Ngcobo, Moulana Eshaaq Osman",
        direction: "ltr",
        source:
          "Islamic Dawah Movement of Southern Africa(IDM), https://www.alqurantranslation.com/",
        comments: "",
        link: { orig: "", la: "", lad: "" },
      },
    ],
  },
];
